swagger: "2.0"
info:
  description: "TechTrain MISSION ã‚²ãƒ¼ãƒ APIå…¥é–€ä»•æ§˜\n
  ã¾ãšã¯ã“ã®APIä»•æ§˜ã«æ²¿ã£ã¦æ©Ÿèƒ½ã‚’å®Ÿè£…ã—ã¦ã¿ã¾ã—ã‚‡ã†ã€‚\n
  \n
  ã“ã®ç”»é¢ã®å„APIã®ã€ŒTry it outã€->ã€ŒExecuteã€ã‚’åˆ©ç”¨ã™ã‚‹ã“ã¨ã§\n
  ãƒ­ãƒ¼ã‚«ãƒ«ç’°å¢ƒã§èµ·å‹•ä¸­ã®APIã«APIãƒªã‚¯ã‚¨ã‚¹ãƒˆã‚’ã™ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚"
  version: "1.0.0"
  title: "TechTrain MISSION Game API"
host: "localhost:8080"
tags:
  - name: "user"
    description: "ãƒ¦ãƒ¼ã‚¶é–¢é€£API"
  - name: "gacha"
    description: "ã‚¬ãƒãƒ£é–¢é€£API"
  - name: "character"
    description: "ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼é–¢é€£API"
schemes:
  - "http"
paths:
  /user/create:
    post:
      tags:
        - "user"
      summary: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±ä½œæˆAPI"
      description: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±ã‚’ä½œæˆã—ã¾ã™ã€‚\n
      ãƒ¦ãƒ¼ã‚¶ã®åå‰æƒ…å ±ã‚’ãƒªã‚¯ã‚¨ã‚¹ãƒˆã§å—ã‘å–ã‚Šã€ãƒ¦ãƒ¼ã‚¶IDã¨èªè¨¼ç”¨ã®ãƒˆãƒ¼ã‚¯ãƒ³ã‚’ç”Ÿæˆã—ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹ã¸ä¿å­˜ã—ã¾ã™ã€‚"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Request Body"
          required: true
          schema:
            $ref: "#/definitions/UserCreateRequest"
      responses:
        200:
          "description": "A successful response."
          "schema":
            "$ref": "#/definitions/UserCreateResponse"

  /user/get:
    get:
      tags:
        - "user"
      summary: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±å–å¾—API"
      description: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±ã‚’å–å¾—ã—ã¾ã™ã€‚\n
      ãƒ¦ãƒ¼ã‚¶ã®èªè¨¼ã¨ç‰¹å®šã®å‡¦ç†ã¯ãƒªã‚¯ã‚¨ã‚¹ãƒˆãƒ˜ãƒƒãƒ€ã®x-tokenã‚’èª­ã¿å–ã£ã¦ãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹ã«ç…§ä¼šã‚’ã—ã¾ã™ã€‚"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "x-token"
          description: "èªè¨¼ãƒˆãƒ¼ã‚¯ãƒ³"
          required: true
          type: "string"
      responses:
        200:
          "description": "A successful response."
          "schema":
            "$ref": "#/definitions/UserGetResponse"

  /user/update:
    put:
      tags:
        - "user"
      summary: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±æ›´æ–°API"
      description: "ãƒ¦ãƒ¼ã‚¶æƒ…å ±ã®æ›´æ–°ã‚’ã—ã¾ã™ã€‚\n
      åˆæœŸå®Ÿè£…ã§ã¯åå‰ã®æ›´æ–°ã‚’è¡Œã„ã¾ã™ã€‚"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "x-token"
          description: "èªè¨¼ãƒˆãƒ¼ã‚¯ãƒ³"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Request Body"
          required: true
          schema:
            $ref: "#/definitions/UserUpdateRequest"
      responses:
        200:
          "description": "A successful response."

  /gacha/draw:
    post:
      tags:
        - "gacha"
      summary: "ã‚¬ãƒãƒ£å®Ÿè¡ŒAPI"
      description: "ã‚¬ãƒãƒ£ã‚’å¼•ã„ã¦ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã‚’å–å¾—ã™ã‚‹å‡¦ç†ã‚’å®Ÿè£…ã—ã¾ã™ã€‚\n
      ç²å¾—ã—ãŸã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã¯ãƒ¦ãƒ¼ã‚¶æ‰€æŒã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ãƒ†ãƒ¼ãƒ–ãƒ«ã¸ä¿å­˜ã—ã¾ã™ã€‚\n
      åŒã˜ç¨®é¡ã®ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã§ã‚‚ãƒ¦ãƒ¼ã‚¶ã¯è¤‡æ•°æ‰€æŒã™ã‚‹ã“ã¨ãŒã§ãã¾ã™ã€‚\n
      \n
      ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®ç¢ºç‡ã¯ç­‰å€ã§ã¯ãªãã€ä»»æ„ã«å¤‰æ›´ã§ãã‚‹ã‚ˆã†ãƒ†ãƒ¼ãƒ–ãƒ«ã‚’è¨­è¨ˆã—ã¾ã—ã‚‡ã†ã€‚"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "x-token"
          description: "èªè¨¼ãƒˆãƒ¼ã‚¯ãƒ³"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Request Body"
          required: true
          schema:
            $ref: "#/definitions/GachaDrawRequest"
      responses:
        200:
          "description": "A successful response."
          "schema":
            "$ref": "#/definitions/GachaDrawResponse"

  /character/list:
    get:
      tags:
        - "character"
      summary: "ãƒ¦ãƒ¼ã‚¶æ‰€æŒã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ä¸€è¦§å–å¾—API"
      description: "ã¦ãƒ¼ã‚¶ãŒæ‰€æŒã—ã¦ã„ã‚‹ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ä¸€è¦§æƒ…å ±ã‚’å–å¾—ã—ã¾ã™ã€‚"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "x-token"
          description: "èªè¨¼ãƒˆãƒ¼ã‚¯ãƒ³"
          required: true
          type: "string"
      responses:
        200:
          "description": "A successful response."
          "schema":
            "$ref": "#/definitions/CharacterListResponse"

definitions:
  UserCreateRequest:
    type: "object"
    properties:
      name:
        type: "string"
        description: "ãƒ¦ãƒ¼ã‚¶å"
  UserCreateResponse:
    type: "object"
    properties:
      token:
        type: "string"
        description: "ã‚¯ãƒ©ã‚¤ã‚¢ãƒ³ãƒˆå´ã§ä¿å­˜ã™ã‚‹ãƒˆãƒ¼ã‚¯ãƒ³"
  UserGetResponse:
    type: "object"
    properties:
      name:
        type: "string"
        description: "ãƒ¦ãƒ¼ã‚¶å"
  UserUpdateRequest:
    type: "object"
    properties:
      name:
        type: "string"
        description: "ãƒ¦ãƒ¼ã‚¶å"
  GachaDrawRequest:
    type: "object"
    properties:
      times:
        type: "integer"
        description: "å®Ÿè¡Œå›æ•°"
  GachaDrawResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/GachaResult"
  GachaResult:
    type: "object"
    properties:
      characterID:
        type: "string"
        description: "ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ID"
      name:
        type: "string"
        description: "ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼å"
  CharacterListResponse:
    type: "object"
    properties:
      characters:
        type: "array"
        items:
          $ref: "#/definitions/UserCharacter"
  UserCharacter:
    type: "object"
    properties:
      userCharacterID:
        type: "string"
        description: "ãƒ¦ãƒ‹ãƒ¼ã‚¯ID"
      characterID:
        type: "string"
        description: "ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ID"
      name:
        type: "string"
        description: "ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼å"
